apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux-devops-blapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-readonly
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: test-blapi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-psp-devops-blapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-psp
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: test-blapi
